from app.database import Base,engine,SessionLocal
from app.models import *
CAREERS=[('soc-analyst','SOC Analyst','Defensive','Monitor, investigate and respond to security alerts and incidents.','Beginner'),('penetration-tester','Penetration Tester','Offensive','Assess systems and applications for exploitable weaknesses.','Beginner'),('cloud-security-engineer','Cloud Security Engineer','Cloud','Secure cloud infrastructure, identities, workloads and services.','Intermediate'),('application-security-engineer','Application Security Engineer','AppSec','Build security into software development and application lifecycles.','Intermediate'),('dfir-analyst','DFIR Analyst','DFIR','Investigate digital evidence and respond to security incidents.','Intermediate'),('devsecops-engineer','DevSecOps Engineer','Security Engineering','Integrate security into software delivery and infrastructure.','Intermediate')]
SKILLS=[('python','Python','Programming','Beginner','Automation, scripting and security tooling.'),('networking','Networking','Fundamentals','Beginner','TCP/IP, DNS, HTTP, routing and packet analysis.'),('linux','Linux','Systems','Beginner','Linux command line, permissions, processes and services.'),('siem','SIEM','Defensive Security','Intermediate','Centralized collection, correlation and investigation of logs.'),('web-security','Web Security','Application Security','Intermediate','Common web vulnerabilities and application testing.'),('cloud-security','Cloud Security','Cloud','Intermediate','Identity, network, workload and data security in cloud environments.'),('incident-response','Incident Response','Defensive Security','Intermediate','Detection, triage, containment, eradication and recovery.'),('secure-coding','Secure Coding','Application Security','Intermediate','Security-aware software design and implementation.'),('git','Git','Developer Tools','Beginner','Version control and collaborative software workflows.'),('sql','SQL','Data','Beginner','Querying and understanding relational databases.')]
TOOLS=[('wireshark','Wireshark','Network Analysis','Beginner','Analyze packets and network traffic.'),('nmap','Nmap','Network Security','Beginner','Discover hosts, ports and services.'),('burp-suite','Burp Suite','Web Security','Beginner','Test and inspect web applications.'),('microsoft-sentinel','Microsoft Sentinel','SIEM','Intermediate','Cloud-native SIEM and security analytics.'),('splunk','Splunk','SIEM','Intermediate','Search and analyze security data.'),('metasploit','Metasploit','Penetration Testing','Intermediate','Framework for security testing.'),('linux-cli','Linux CLI','Systems','Beginner','Command-line administration and analysis.'),('git','Git','Developer Tools','Beginner','Version control.')]
MAP={'soc-analyst':['networking','linux','siem','incident-response','python'],'penetration-tester':['networking','linux','python','web-security'],'cloud-security-engineer':['networking','linux','cloud-security','python'],'application-security-engineer':['web-security','secure-coding','python','sql'],'dfir-analyst':['linux','networking','incident-response','python'],'devsecops-engineer':['python','linux','cloud-security','secure-coding','git']}
TOOLMAP={'soc-analyst':['wireshark','microsoft-sentinel','splunk'],'penetration-tester':['nmap','burp-suite','metasploit'],'cloud-security-engineer':['linux-cli','nmap'],'application-security-engineer':['burp-suite','git'],'dfir-analyst':['wireshark','linux-cli'],'devsecops-engineer':['git','linux-cli']}
PHASES={'soc-analyst':['Cybersecurity Fundamentals','Networking','Linux','Windows Security','SIEM','Log Analysis','Incident Response','Projects','Internships'], 'penetration-tester':['Cybersecurity Fundamentals','Networking','Linux','Web Security','Burp Suite','Nmap','Metasploit','Projects','CTFs'], 'cloud-security-engineer':['Networking','Linux','Cloud Fundamentals','Identity & Access','Cloud Security','Monitoring','Projects'], 'application-security-engineer':['Programming','Web Fundamentals','Web Security','Secure Coding','Burp Suite','Threat Modeling','Projects'], 'dfir-analyst':['Networking','Linux','Windows Artifacts','Incident Response','Digital Forensics','Threat Hunting','Projects'], 'devsecops-engineer':['Python','Git','Linux','Cloud Fundamentals','CI/CD','Cloud Security','Secure Coding','Projects']}
JOBS=[('SOC Analyst Intern','Demo Security Labs','Hyderabad, India','Internship','Networking, Linux, SIEM, Python','Student','2 days ago','https://example.com/selenite-demo-job'),('Junior Penetration Tester','Demo CyberWorks','Remote, India','Full-time','Linux, Web Security, Burp Suite, Nmap','0-1 years','5 days ago','https://example.com/selenite-demo-job'),('Cloud Security Intern','Demo CloudSec','Bengaluru, India','Internship','Cloud Security, Linux, Python','Student','1 week ago','https://example.com/selenite-demo-job')]
EVENTS=[('OWASP Community Meetup','Community','Hyderabad','2026-10-10','https://owasp.org/events/','Yes'),('Capture The Flag Practice Night','CTF','Online','2026-10-18','https://ctftime.org/','Yes'),('Cybersecurity Career Workshop','Workshop','Online','2026-10-25','https://example.com/event','Yes')]
NEWS=[('Cybersecurity advisory feed placeholder','CISA','Vulnerabilities','Live connector ready','Review official advisory feed.','https://www.cisa.gov/cybersecurity-advisories','No')]
TRENDS=[('SOC Analyst','SIEM','India','2026-Q3',86,120,'Demo seed dataset; replace with sourced job-description aggregation.'),('SOC Analyst','Networking','India','2026-Q3',78,120,'Demo seed dataset; replace with sourced job-description aggregation.'),('Cloud Security Engineer','Cloud Security','India','2026-Q3',91,95,'Demo seed dataset; replace with sourced job-description aggregation.'),('Application Security Engineer','Secure Coding','India','2026-Q3',88,80,'Demo seed dataset; replace with sourced job-description aggregation.')]
def seed():
 Base.metadata.create_all(engine); db=SessionLocal()
 if db.query(Career).count(): db.close(); return
 skills={};tools={};careers={}
 for x in SKILLS: o=Skill(slug=x[0],name=x[1],category=x[2],difficulty=x[3],description=x[4]);db.add(o);skills[x[0]]=o
 for x in TOOLS: o=Tool(slug=x[0],name=x[1],category=x[2],difficulty=x[3],description=x[4]);db.add(o);tools[x[0]]=o
 for x in CAREERS: o=Career(slug=x[0],name=x[1],category=x[2],description=x[3],level=x[4]);db.add(o);careers[x[0]]=o
 db.flush()
 for c,ss in MAP.items():
  for s in ss: db.add(CareerSkill(career_id=careers[c].id,skill_id=skills[s].id))
 for c,ts in TOOLMAP.items():
  for t in ts: db.add(CareerTool(career_id=careers[c].id,tool_id=tools[t].id))
 for j in JOBS: db.add(Job(title=j[0],company=j[1],location=j[2],kind=j[3],skills=j[4],experience=j[5],posted=j[6],source_url=j[7],demo=True))
 for e in EVENTS: db.add(Event(title=e[0],kind=e[1],location=e[2],date=e[3],url=e[4],free=True,demo=True))
 for n in NEWS: db.add(News(title=n[0],source=n[1],category=n[2],published=n[3],summary=n[4],url=n[5],demo=True))
 for t in TRENDS: db.add(MarketTrend(role=t[0],skill=t[1],region=t[2],period=t[3],demand_index=t[4],sample_size=t[5],source=t[6]))
 db.commit();db.close()
if __name__=='__main__': seed()
