const API=localStorage.getItem('selenite_api')||'http://127.0.0.1:8000';
const demoCareers=[{slug:'soc-analyst',name:'SOC Analyst',category:'Defensive',description:'Monitor, investigate and respond to security alerts and incidents.',level:'Beginner'},{slug:'penetration-tester',name:'Penetration Tester',category:'Offensive',description:'Assess systems and applications for exploitable weaknesses.',level:'Beginner'},{slug:'cloud-security-engineer',name:'Cloud Security Engineer',category:'Cloud',description:'Secure cloud infrastructure, identities and workloads.',level:'Intermediate'},{slug:'application-security-engineer',name:'Application Security Engineer',category:'AppSec',description:'Build security into software development and application lifecycles.',level:'Intermediate'},{slug:'dfir-analyst',name:'DFIR Analyst',category:'DFIR',description:'Investigate digital evidence and respond to incidents.',level:'Intermediate'},{slug:'devsecops-engineer',name:'DevSecOps Engineer',category:'Security Engineering',description:'Integrate security into software delivery and infrastructure.',level:'Intermediate'}];
const phases={
'soc-analyst':['Cybersecurity Fundamentals','Networking','Linux','Windows Security','SIEM','Log Analysis','Incident Response','Projects','Internships'],
'penetration-tester':['Cybersecurity Fundamentals','Networking','Linux','Web Security','Burp Suite','Nmap','Metasploit','Projects','CTFs'],
'cloud-security-engineer':['Networking','Linux','Cloud Fundamentals','Identity & Access','Cloud Security','Monitoring','Projects'],
'application-security-engineer':['Programming','Web Fundamentals','Web Security','Secure Coding','Burp Suite','Threat Modeling','Projects'],
'dfir-analyst':['Networking','Linux','Windows Artifacts','Incident Response','Digital Forensics','Threat Hunting','Projects'],
'devsecops-engineer':['Python','Git','Linux','Cloud Fundamentals','CI/CD','Cloud Security','Secure Coding','Projects']};
const fallbackSkills=[['python','Python','Programming'],['networking','Networking','Fundamentals'],['linux','Linux','Systems'],['siem','SIEM','Defensive Security'],['web-security','Web Security','Application Security'],['cloud-security','Cloud Security','Cloud'],['incident-response','Incident Response','Defensive Security'],['secure-coding','Secure Coding','Application Security'],['git','Git','Developer Tools'],['sql','SQL','Data']].map(x=>({slug:x[0],name:x[1],category:x[2],difficulty:'Beginner',description:'Core cybersecurity career skill.'}));
const fallbackTools=[['wireshark','Wireshark','Network Analysis'],['nmap','Nmap','Network Security'],['burp-suite','Burp Suite','Web Security'],['microsoft-sentinel','Microsoft Sentinel','SIEM'],['splunk','Splunk','SIEM'],['metasploit','Metasploit','Penetration Testing']].map(x=>({slug:x[0],name:x[1],category:x[2],difficulty:'Beginner',description:'Security analysis and practice tool.'}));
let state={user:JSON.parse(localStorage.getItem('selenite_user')||'null'),token:localStorage.getItem('selenite_token')||'',route:location.hash.slice(1)||'home'};
async function api(path,opts={}){try{opts.headers={...(opts.headers||{}),...(state.token?{Authorization:'Bearer '+state.token}:{})};const r=await fetch(API+path,opts);if(!r.ok)throw Error(await r.text());return await r.json()}catch(e){return null}}
function save(){localStorage.setItem('selenite_user',JSON.stringify(state.user||null));if(state.token)localStorage.setItem('selenite_token',state.token);else localStorage.removeItem('selenite_token')}
function esc(x){return String(x??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function nav(){return `<header class="top"><a class="brand" href="#home">◐ <span>SELENITE</span></a><nav class="topnav"><a href="#careers">Explore</a><a href="#roadmap">Learn</a><a href="#jobs">Opportunities</a><a href="#news">Intel</a><a href="#ai">AI</a>${state.user?`<a href="#profile">${esc(state.user.name)}</a>`:`<a href="#login">Login</a>`}</nav></header>`}
function sidebar(){let links=[['dashboard','Dashboard'],['careers','Careers'],['skills','Skills'],['tools','Tools'],['roadmap','Roadmaps'],['progress','Progress'],['jobs','Jobs'],['internships','Internships'],['events','Hackathons / CTFs'],['news','Cyber News'],['market','Market Intel'],['ai','AI Assistant'],['resume','Resume Analyzer'],['profile','Profile'],['settings','Settings']];return `<aside><div class="side-title">SELENITE OS</div><div class="side">${links.map(x=>`<a class="${state.route===x[0]?'active':''}" href="#${x[0]}">${x[1]}</a>`).join('')}</div></aside>`}
function bottom(){return `<div class="bottom"><a href="#dashboard">Home</a><a href="#careers">Explore</a><a href="#roadmap">Learn</a><a href="#jobs">Jobs</a><a href="#ai">AI</a></div>`}
function shell(content){return `${nav()}<div class="layout">${sidebar()}<main>${content}</main></div>${bottom()}`}
function card(c){return `<div class="card">${c}</div>`}
async function renderHome(){if(state.user)return renderDashboard();document.getElementById('app').innerHTML=`${nav()}<main><section class="hero"><span class="eyebrow">CYBERSECURITY CAREER INTELLIGENCE OS</span><h1>Build your cybersecurity career with clarity.</h1><p>Explore roles, master skills, follow a roadmap, understand market signals, discover opportunities and track progress in one moonlit workspace.</p><div class="actions"><a class="btn" href="#signup">Start your journey</a><a class="btn ghost" href="#careers">Explore careers</a></div></section>${bottom()}</main>`}
async function renderAuth(type){document.getElementById('app').innerHTML=`<main class="auth"><div class="authbox">${card(`<div class="brand">◐ SELENITE</div><h1>${type==='signup'?'Create your profile':'Welcome back'}</h1><p class="sub">${type==='signup'?'Your career intelligence workspace starts here.':'Continue your roadmap and progress.'}</p>${type==='signup'?`<input class="field" id="name" placeholder="Name"><input class="field" id="email" placeholder="Email"><input class="field" id="password" type="password" placeholder="Password"><select class="field" id="career">${demoCareers.map(c=>`<option value="${c.slug}">${c.name}</option>`).join('')}</select><select class="field" id="level"><option>Beginner</option><option>Intermediate</option><option>Advanced</option></select><button class="btn" onclick="doSignup()">Create account</button><p><a href="#login">Already have an account?</a></p>`:`<input class="field" id="email" placeholder="Email"><input class="field" id="password" type="password" placeholder="Password"><button class="btn" onclick="doLogin()">Login</button><p><a href="#signup">Create account</a></p>`}`)}</div></main>`}
async function doSignup(){let payload={name:val('name'),email:val('email'),password:val('password'),target_career:val('career'),level:val('level')};let r=await api('/api/auth/register',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});if(!r)return alert('Backend not running. Start FastAPI first.');state.token=r.access_token;state.user=r.user;save();location.hash='#dashboard'}
async function doLogin(){let r=await api('/api/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email:val('email'),password:val('password')})});if(!r)return alert('Login failed. Check backend and credentials.');state.token=r.access_token;state.user=r.user;save();location.hash='#dashboard'}
function val(id){return document.getElementById(id)?.value||''}
async function renderDashboard(){let u=state.user||{};let c=u.target_career||'soc-analyst';let p=phases[c]||phases['soc-analyst'];let rows=state.token?await api('/api/progress'):null;let done=new Set((rows||[]).filter(x=>x.career_slug===c&&x.completed).map(x=>x.phase_index));let pct=Math.round(done.size/p.length*100);let gap=state.token?await api('/api/skill-gap'):null;document.getElementById('app').innerHTML=shell(`<span class="eyebrow">YOUR COMMAND CENTER</span><h1>Good evening, ${esc(u.name||'Explorer')} 👋</h1><p class="sub">Target career: <b>${esc((demoCareers.find(x=>x.slug===c)||{}).name||c)}</b></p><div class="grid grid4" style="margin:24px 0">${[['Roadmap',pct+'%'],['Completed',done.size],['Next steps',p.length-done.size],['Skill gaps',gap?.missing?.length??'—']].map(x=>card(`<div class="kpi"><span class="stat">${x[1]}</span><small>${x[0]}</small></div>`)).join('')}</div><div class="grid"><div class="card"><h2>Continue roadmap</h2><p class="sub">${esc(p.find((_,i)=>!done.has(i))||'Roadmap complete 🎉')}</p><a class="btn" href="#roadmap">Open roadmap</a></div><div class="card"><h2>Skill gap</h2><p class="sub">${gap?esc(gap.missing.join(', ')||'No mapped gaps'): 'Sign in to calculate your skill gap.'}</p><a class="btn ghost" href="#skills">Build skills</a></div><div class="card"><h2>Opportunities</h2><p class="sub">Explore jobs, internships and student events connected to cybersecurity.</p><a class="btn ghost" href="#jobs">Explore jobs</a></div></div>`)}
async function renderCareers(){let q=encodeURIComponent(new URLSearchParams(location.hash.split('?')[1]||'').get('q')||'');let data=await api('/api/careers?search='+q)||demoCareers;document.getElementById('app').innerHTML=shell(`<h1>Career Explorer</h1><p class="sub">Understand roles, skills, tools and learning paths.</p><div class="toolbar"><input class="field search" id="careerQ" placeholder="Search careers..." oninput="filterCards()"></div><div id="careerGrid" class="grid">${data.map(c=>card(`<span class="tag">${esc(c.category)}</span><h2>${esc(c.name)}</h2><p class="sub">${esc(c.description)}</p><span class="tag">${esc(c.level)}</span><div class="actions"><a class="btn small" href="#career/${c.slug}">View role</a><a class="btn small ghost" href="#roadmap?career=${c.slug}">Roadmap</a></div>`)).join('')}</div>`)}
async function renderCareerDetail(slug){let c=await api('/api/careers/'+slug);if(!c){let d=demoCareers.find(x=>x.slug===slug)||demoCareers[0];c={...d,skills:['Networking','Linux','Python','SIEM','Incident Response'],tools:['Wireshark','Microsoft Sentinel','Splunk'],roadmap:(phases[slug]||phases['soc-analyst']).map((name,index)=>({name,index,completed:false}))}}document.getElementById('app').innerHTML=shell(`<a class="sub" href="#careers">← Careers</a><h1 style="margin-top:12px">${esc(c.name)}</h1><p class="sub">${esc(c.description)}</p><div class="grid" style="margin-top:24px"><div class="card"><h2>Core skills</h2>${c.skills.map(s=>`<span class="tag">${esc(s)}</span>`).join('')}</div><div class="card"><h2>Tools</h2>${c.tools.map(s=>`<span class="tag">${esc(s)}</span>`).join('')}</div></div><div class="card" style="margin-top:18px"><h2>Roadmap</h2>${c.roadmap.slice(0,8).map((x,i)=>`<div class="phase"><span>◐</span><div><b>${i+1}. ${esc(x.name)}</b><div class="sub">Learn → practice → project</div></div></div>`).join('')}<a class="btn" href="#roadmap?career=${slug}">Use this roadmap</a></div>`)}
async function renderSkills(){let data=await api('/api/skills')||fallbackSkills;document.getElementById('app').innerHTML=shell(`<h1>Skill Explorer</h1><p class="sub">Map skills to roles and your personal gap.</p><div class="toolbar"><input class="field search" id="skillQ" placeholder="Search skills..." oninput="filterCards()"></div><div id="skillGrid" class="grid">${data.map(s=>card(`<span class="tag">${esc(s.category)}</span><h2>${esc(s.name)}</h2><p class="sub">${esc(s.description)}</p><span class="tag">${esc(s.difficulty)}</span>${state.user?`<button class="btn small" onclick="markSkill('${s.slug}')">Mark learned</button>`:''}`)).join('')}</div>`)}
async function markSkill(slug){let r=await api('/api/me/skills',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({skill_slug:slug,level:3})});alert(r?'Skill saved.':'Please login and start backend.')}
async function renderTools(){let data=await api('/api/tools')||fallbackTools;document.getElementById('app').innerHTML=shell(`<h1>Tool Explorer</h1><p class="sub">Discover the tools commonly used across security roles.</p><div class="grid">${data.map(t=>card(`<span class="tag">${esc(t.category)}</span><h2>${esc(t.name)}</h2><p class="sub">${esc(t.description)}</p><span class="tag">${esc(t.difficulty)}</span>`)).join('')}</div>`)}
async function renderRoadmap(){let qs=new URLSearchParams(location.hash.split('?')[1]||'');let c=qs.get('career')||state.user?.target_career||'soc-analyst';let data=await api('/api/roadmaps/'+c);let list=data?.phases||phases[c] .map((name,index)=>({name,index,completed:false}));let prog=state.token?await api('/api/progress'):null;let done=new Set((prog||[]).filter(x=>x.career_slug===c&&x.completed).map(x=>x.phase_index));document.getElementById('app').innerHTML=shell(`<h1>Roadmap Engine</h1><p class="sub">Career: <b>${esc((demoCareers.find(x=>x.slug===c)||{}).name||c)}</b></p><div class="card" style="margin:20px 0"><div class="row"><b>${done.size}/${list.length} phases</b><span>${Math.round(done.size/list.length*100)}%</span></div><div class="progress" style="margin-top:10px"><div style="width:${Math.round(done.size/list.length*100)}%"></div></div></div><div class="card">${list.map((x,i)=>`<div class="phase"><input type="checkbox" ${done.has(i)?'checked':''} onchange="toggleProgress('${c}',${i},this.checked)"><div><b>${i+1}. ${esc(x.name)}</b><div class="sub">Topics · practice · project · opportunity</div></div><span class="${done.has(i)?'success':''}">${done.has(i)?'●':'○'}</span></div>`).join('')}</div>`)}
async function toggleProgress(c,i,checked){if(!state.token)return alert('Login first to sync progress.');await api('/api/progress?career_slug='+encodeURIComponent(c),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({phase_index:i,completed:checked})});renderRoadmap()}
async function renderProgress(){let rows=state.token?await api('/api/progress'):null;let c=state.user?.target_career||'soc-analyst';let p=phases[c]||phases['soc-analyst'];let done=new Set((rows||[]).filter(x=>x.career_slug===c&&x.completed).map(x=>x.phase_index));document.getElementById('app').innerHTML=shell(`<h1>Progress</h1><p class="sub">Your progress is tied to your target role and roadmap.</p><div class="grid grid4">${card(`<div class="stat">${Math.round(done.size/p.length*100)}%</div><div class="sub">Overall roadmap</div>`)}${card(`<div class="stat">${done.size}</div><div class="sub">Completed</div>`)}${card(`<div class="stat">${p.length-done.size}</div><div class="sub">Remaining</div>`)}</div><div class="card" style="margin-top:18px">${p.map((x,i)=>`<div class="phase"><span>${done.has(i)?'●':'○'}</span><div><b>${esc(x)}</b><div class="sub">${done.has(i)?'Completed':'Not completed yet'}</div></div></div>`).join('')}</div>`)}
async function renderJobs(){let data=await api('/api/jobs')||[{title:'SOC Analyst Intern',company:'Demo Security Labs',location:'Hyderabad, India',kind:'Internship',skills:'Networking, Linux, SIEM, Python',experience:'Student',posted:'2 days ago',source_url:'#',demo:true},{title:'Junior Penetration Tester',company:'Demo CyberWorks',location:'Remote, India',kind:'Full-time',skills:'Linux, Web Security, Burp Suite, Nmap',experience:'0-1 years',posted:'5 days ago',source_url:'#',demo:true}];document.getElementById('app').innerHTML=shell(`<h1>Jobs</h1><p class="sub">Opportunity data is clearly marked when it is demo data. Production connectors should use permitted APIs/feeds.</p><div class="notice">V1 includes a working job data layer and demo seed records. Replace demo records with an approved jobs API/feed before public launch.</div><div class="toolbar"><input class="field search" placeholder="Role or skill" oninput="filterCards()"><select class="field"><option>All locations</option><option>Hyderabad</option><option>Remote</option></select></div><div class="grid" id="jobGrid">${data.map(j=>card(`<div class="row"><span class="tag">${esc(j.kind)}</span>${j.demo?'<span class="demo">DEMO</span>':''}</div><h2>${esc(j.title)}</h2><p><b>${esc(j.company)}</b> · ${esc(j.location)}</p><p class="sub">Skills: ${esc(j.skills)}</p><p class="sub">${esc(j.experience)} · ${esc(j.posted)}</p><a class="btn small" href="${esc(j.source_url)}" target="_blank">Original listing</a>`)).join('')}</div>`)}
async function renderInternships(){let data=await api('/api/jobs?kind=Internship')||[{title:'SOC Analyst Intern',company:'Demo Security Labs',location:'Hyderabad, India',kind:'Internship',skills:'Networking, Linux, SIEM, Python',experience:'Student',posted:'2 days ago',source_url:'#',demo:true}];document.getElementById('app').innerHTML=shell(`<h1>Internships</h1><p class="sub">Student/fresher opportunities. Demo records are labelled.</p><div class="grid">${data.map(j=>card(`<span class="tag">${esc(j.kind)}</span>${j.demo?'<span class="demo">DEMO</span>':''}<h2>${esc(j.title)}</h2><p><b>${esc(j.company)}</b> · ${esc(j.location)}</p><p class="sub">Skills: ${esc(j.skills)}</p><p class="sub">${esc(j.experience)} · ${esc(j.posted)}</p><a class="btn small" href="${esc(j.source_url)}" target="_blank">Original listing</a>`)).join('')}</div>`)}
async function renderEvents(){let data=await api('/api/events')||[];document.getElementById('app').innerHTML=shell(`<h1>Hackathons & CTFs</h1><p class="sub">Student-friendly events and practice opportunities.</p><div class="grid">${data.map(e=>card(`<span class="tag">${esc(e.kind)}</span>${e.demo?'<span class="demo">DEMO</span>':''}<h2>${esc(e.title)}</h2><p class="sub">${esc(e.location)} · ${esc(e.date)}</p><a class="btn small" href="${esc(e.url)}" target="_blank">Event site</a>`)).join('')}</div>`)}
async function renderNews(){let data=await api('/api/news')||[];document.getElementById('app').innerHTML=shell(`<h1>Cyber News</h1><p class="sub">News is linked back to original sources. Do not copy full articles.</p><div class="grid">${data.map(n=>card(`<span class="tag">${esc(n.category)}</span>${n.demo?'<span class="demo">DEMO</span>':''}<h2>${esc(n.title)}</h2><p class="sub">${esc(n.source)} · ${esc(n.published)}</p><p>${esc(n.summary)}</p><a class="btn small" href="${esc(n.url)}" target="_blank">Original source</a>`)).join('')}</div>`)}
async function renderMarket(){let data=await api('/api/market')||[];document.getElementById('app').innerHTML=shell(`<h1>Market Intel</h1><p class="sub">Skill-demand signals should always show period, geography and sample size.</p><div class="notice">Seed trends are demo data and must not be presented as current universal market requirements. Replace them with a documented job-description aggregation pipeline.</div><div class="grid">${data.map(t=>card(`<span class="tag">${esc(t.region)}</span><h2>${esc(t.skill)}</h2><p class="sub">Role: ${esc(t.role)} · ${esc(t.period)}</p><div class="stat">${t.demand_index}</div><p class="sub">Demand index · sample ${t.sample_size}</p><small>${esc(t.source)}</small>`)).join('')}</div>`)}
async function renderAI(){document.getElementById('app').innerHTML=shell(`<h1>CyberCareer AI</h1><p class="sub">A grounded career assistant. V1 uses Selenite's structured career data; an LLM connector can be added through the backend environment.</p><div class="card"><div id="chat" class="chat"><div class="bubble ai">Hi. Ask me what to learn next, what skills you are missing, or how to prepare for your target role.</div></div><div class="toolbar"><input class="field search" id="chatInput" placeholder="e.g. What should I learn next for SOC?"><button class="btn" onclick="sendChat()">Ask</button></div></div>`)}
async function sendChat(){let msg=val('chatInput');if(!msg)return;let chat=document.querySelector('#chat');chat.innerHTML+=`<div class="bubble user">${esc(msg)}</div>`;let r=await api('/api/ai/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({message:msg})});chat.innerHTML+=`<div class="bubble ai">${esc(r?.answer||'Start the backend and sign in to use the assistant.')}</div>`;document.querySelector('#chatInput').value=''}
async function renderResume(){document.getElementById('app').innerHTML=shell(`<h1>Resume Analyzer</h1><p class="sub">Paste resume text and compare it to a target role. This MVP explains skills and gaps; it does not invent an ATS score.</p><div class="grid"><div class="card"><select class="field" id="resumeRole">${demoCareers.map(c=>`<option value="${c.slug}">${c.name}</option>`).join('')}</select><textarea class="field" id="resumeText" rows="18" placeholder="Paste resume text here..."></textarea><button class="btn" onclick="analyzeResume()">Analyze</button></div><div class="card" id="resumeResult"><h2>Analysis</h2><p class="sub">Your result will appear here.</p></div></div>`)}
async function analyzeResume(){let r=await api('/api/resume/analyze',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({target_role:val('resumeRole'),text:val('resumeText')})});if(!r)return alert('Login and start the backend first.');document.querySelector('#resumeResult').innerHTML=`<h2>Analysis</h2><p class="success">Found: ${esc(r.found_skills.join(', ')||'None')}</p><p class="dangerText">Missing: ${esc(r.missing_skills.join(', ')||'None')}</p><h3>Suggested project</h3><p>${esc(r.projects_suggested.join(' · '))}</p><small>${esc(r.note)}</small>`}
async function renderProfile(){let u=state.token?await api('/api/me'):state.user;document.getElementById('app').innerHTML=shell(`<h1>Profile</h1><div class="card"><h2>${esc(u?.name||'Guest')}</h2><p class="sub">${esc(u?.email||'')}</p><p>Target career: <b>${esc(u?.target_career||'Not set')}</b></p><p>Level: <b>${esc(u?.level||'')}</b></p><button class="btn danger" onclick="logout()">Log out</button></div>`)}
function logout(){state.user=null;state.token='';save();location.hash='#home'}
async function renderSettings(){document.getElementById('app').innerHTML=shell(`<h1>Settings</h1><div class="card"><h2>API endpoint</h2><p class="sub">Change this only if your backend runs somewhere else.</p><input class="field" id="apiUrl" value="${esc(API)}"><button class="btn" onclick="localStorage.setItem('selenite_api',val('apiUrl'));alert('Saved. Reload the app.')">Save API URL</button></div><div class="card" style="margin-top:18px"><h2>Development status</h2><p class="sub">Local authentication, roadmap sync, skill tracking and resume analysis are enabled. Production hardening still requires HTTPS, secret management, PostgreSQL migrations, rate limiting, monitoring and an approved live data source strategy.</p></div>`)}
function filterCards(){let q=(event?.target?.value||'').toLowerCase();document.querySelectorAll('.grid .card').forEach(c=>c.style.display=c.innerText.toLowerCase().includes(q)?'':'none')}
async function render(){state.route=location.hash.slice(1)||'home';let r=state.route.split('?')[0];let slug=r.startsWith('career/')?r.split('/')[1]:null;switch(r){case'home':return renderHome();case'login':return renderAuth('login');case'signup':return renderAuth('signup');case'dashboard':return renderDashboard();case'careers':return renderCareers();case'skills':return renderSkills();case'tools':return renderTools();case'roadmap':return renderRoadmap();case'progress':return renderProgress();case'jobs':return renderJobs();case'internships':return renderJobs();case'events':return renderEvents();case'news':return renderNews();case'market':return renderMarket();case'ai':return renderAI();case'resume':return renderResume();case'profile':return renderProfile();case'settings':return renderSettings();default:if(slug)return renderCareerDetail(slug);return renderHome()}}
window.addEventListener('hashchange',render);render();
